### ISSUE TITLE
dcm4chee-arc web ui invalid json

### ISSUE THREAD

**Issue by mdg583** [dcm4che/dcm4chee-arc-light#294] opened 2016-08-05 12:15 UTC
Hello,
I am trying to learn my way around dcm4chee-arc-light. The web ui is throwing console errors when I'm looking at http://myserver/dcm4chee-arc/ui/#/devicelist:

```
angular.min.js:117 Error loading schema ref SyntaxError: Unexpected token s in JSON at position 15483
    at Object.parse (native)
    at xc (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:16:364)
    at dc (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:91:424)
    at http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:92:337
    at r (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:7:355)
    at hd (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:92:319)
    at c (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:94:72)
    at http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:130:409
    at m.$eval (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:145:107)
    at m.$digest (http://myserver/dcm4chee-arc/ui/bower_components/angular/angular.min.js:142:173)
```
I investigated the json (http://myserver/dcm4chee-arc/ui/schema/archiveDevice.schema.json) and the json has `\s` characters. I think the `\` character should be escaped, ie `\\`

**Comment by gunterze** [comment] 2016-08-05 12:36
Duplicate of #292

**Closed by gunterze** 2016-08-05 12:36 UTC
Labels: duplicate
