### ISSUE TITLE
UnsupportedOperationException in ldapXXXConfiguration.loadXXX

### ISSUE THREAD

**Issue by dvdmena** [dcm4che/dcm4chee-arc-light#401] opened 2016-09-29 15:41 UTC
I have get an UnsupportedOperationException in differents point of the deployment process (and after) in some ldapXXXXConfiguration.loadXXX

Caused by: java.lang.UnsupportedOperationException
	at javax.naming.NameClassPair.getNameInNamespace(java.naming@9-ea/NameClassPair.java:256)

I founded it in:

org.dcm4che3.conf.ldap.LdapDicomConfiguration.loadApplicationEntity
org.dcm4che3.conf.ldap.hl7.LdapHL7Configuration.loadHL7Application 
org.dcm4che3.conf.ldap.LdapDicomConfiguration.listAETInfos 

always when a loadChilds(xxx, sr.getNameInNamespace()) is called.

It happens because it try to get a null NameinNameSpace. I solved it surrounding the loadChilds with a try/catch and rebuilding again. 
I have traced the packs from/to the LDAP server and it returns correctly data with no null reference, so I don't know why the iteration get a null value. 

The testing system is:

Ubuntu 16 server / OpenLDAP / Wildfly 10 / Mysql / dcm4che (last github version)/ dcm4chee-arc-light 5.7.0 (last github version)

**Comment by gunterze** [comment] 2016-09-30 08:52
What's your java.naming.provider.url in wildfly-10.0.0.Final/standalone/configuration/dcm4chee-arc/ldap.properties, which JRE, which OpenLDAP version, which configuration content?
We are not able to reproduce the problem with OpenJDK 1.8.0_91 and OpenLDAP 2.4.42, neither with the default, nor the sample configuration.

**Comment by dvdmena** [comment] 2016-09-30 09:25
Java(TM) SE Runtime Environment (build 9-ea+134) 64bits
OpenLDAP: 2.4.44 (Sep 26 2016 14:33:24)

the ldap.properties is the standard one:

java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory
java.naming.ldap.attributes.binary=dicomVendorData
java.naming.provider.url=ldap://127.0.0.1:389/dc=dcm4che,dc=org
java.naming.security.principal=cn=admin,dc=dcm4che,dc=org
java.naming.security.credentials=secret

**Comment by gunterze** [comment] 2016-09-30 12:07
There is some problem with our environment! You should not need to add anything into the naming module. Try with Open JDK 8.

**Comment by dvdmena** [comment] 2016-09-30 13:19
I have tested with openjdk8 and it seams works without Naming errors. Al also delete the module addition. I have to be a java-9 problem.

**Comment by gunterze** [comment] 2016-10-04 11:19
Will be hopefully fixed by the Wildfly team..

**Closed by gunterze** 2016-10-04 11:19 UTC
