### ISSUE TITLE
Export of objects to second storage fails if instances are already purged.

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2150] opened 2019-09-02 09:02 UTC
Issue simulation : 
- Store study to archive -> Purge Instances
- Then, on `Study` level export : Export Task processed with `WARNING`; outcome message as `Could not find study`
Caused by [if (isEmptyOrContains(ctx.getSopInstanceUIDs(), entry.getName())) in RetrieveServiceImpl.java](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-retrieve/src/main/java/org/dcm4chee/arc/retrieve/impl/RetrieveServiceImpl.java#L443) always returning `false`

- On `Series` level export : Fails with following error
````
2019-08-28 15:49:32,108 WARN  [org.dcm4che.arc.export.storage.StorageExporter] (Thread-75 (ActiveMQ-client-global-threads)) Failed to copy Instance[iuid=1.2.840.113674.950809132648168.100,cuid=1.2.840.10008.5.1.4.1.1.4] to Storage[id=fs2, uri=file:/home/vrinda/work/unsecure/wildfly-16.0.0.Final/standalone/data/fs2/]:
: javax.ejb.EJBException: java.lang.NullPointerException
..........
..........
at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-store-5.18.1.jar//org.dcm4chee.arc.store.impl.StoreServiceEJB$$$view16.replaceLocation(Unknown Source)
..........
..........
at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-store-5.18.1.jar//org.dcm4chee.arc.store.impl.StoreServiceEJB$Proxy$_$$_Weld$EnterpriseProxy$.replaceLocation(Unknown Source)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-store-5.18.1.jar//org.dcm4chee.arc.store.impl.StoreServiceImpl.replaceLocation(StoreServiceImpl.java:312)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-store-5.18.1.jar//org.dcm4chee.arc.store.impl.StoreServiceImpl$Proxy$_$$_WeldClientProxy.replaceLocation(Unknown Source)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-export-storage-5.18.1.jar//org.dcm4che.arc.export.storage.StorageExporter.export(StorageExporter.java:133)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-export-mgt-5.18.1.jar//org.dcm4chee.arc.export.mgt.impl.ExportManagerMDB.onMessage(ExportManagerMDB.java:113)
............
............
Caused by: java.lang.NullPointerException
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-store-5.18.1.jar//org.dcm4chee.arc.store.impl.StoreServiceEJB.addLocation(StoreServiceEJB.java:1484)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-store-5.18.1.jar//org.dcm4chee.arc.store.impl.StoreServiceEJB.replaceLocation(StoreServiceEJB.java:1491)
````

- On `Instance` level export : Fails with following error
````
2019-08-28 15:37:09,721 WARN  [org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB] (default task-11) Failed to query Export Task Info for ExportTask[pk=2269, exporterID=CopyToFS2, studyUID=1.2.840.113674.1118.54.200, seriesUID=1.2.840.113674.1118.54.180.300, objectUID=1.2.840.113674.950809132648168.100] - : javax.ejb.EJBTransactionRolledbackException: No entity found for query
............
............
at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-query-5.18.1.jar//org.dcm4chee.arc.query.impl.QueryServiceEJB$Proxy$_$$_Weld$EnterpriseProxy$.queryObjectExportTaskInfo(Unknown Source)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-query-5.18.1.jar//org.dcm4chee.arc.query.impl.QueryServiceImpl.queryExportTaskInfo(QueryServiceImpl.java:272)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-query-5.18.1.jar//org.dcm4chee.arc.query.impl.QueryServiceImpl$Proxy$_$$_WeldClientProxy.queryExportTaskInfo(Unknown Source)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-export-mgt-5.18.1.jar//org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTask(ExportManagerEJB.java:260)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-export-mgt-5.18.1.jar//org.dcm4chee.arc.export.mgt.impl.ExportManagerEJB.scheduleExportTask(ExportManagerEJB.java:215)
............
............
at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-export-mgt-5.18.1.jar//org.dcm4chee.arc.export.mgt.ExportManager$$$view57.scheduleExportTask(Unknown Source)
............
............
at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-export-mgt-5.18.1.jar//org.dcm4chee.arc.export.mgt.impl.ExportManager$1469038282$Proxy$_$$_Weld$EnterpriseProxy$.scheduleExportTask(Unknown Source)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-war-5.18.1-unsecure.war//org.dcm4chee.arc.export.rs.ExporterRS.export(ExporterRS.java:181)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-war-5.18.1-unsecure.war//org.dcm4chee.arc.export.rs.ExporterRS.exportInstance(ExporterRS.java:149)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-war-5.18.1-unsecure.war//org.dcm4chee.arc.export.rs.ExporterRS$Proxy$_$$_WeldClientProxy.exportInstance(Unknown Source)
............
............
Caused by: javax.persistence.NoResultException: No entity found for query
  at org.hibernate@5.3.9.Final//org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1555)
  at org.hibernate@5.3.9.Final//org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:109)
  at deployment.dcm4chee-arc-ear-5.18.1-psql.ear.dcm4chee-arc-query-5.18.1.jar//org.dcm4chee.arc.query.impl.QueryServiceEJB.queryObjectExportTaskInfo(QueryServiceEJB.java:336)
````

**Comment by gunterze** [comment] 2019-09-03 13:42
Cannot reproduce. Probably fixed with https://github.com/dcm4che/dcm4chee-arc-light/commit/03d60fa53ee08d9767430f1332dda69c75ef250e .

**Comment by vrindanayak** [comment] 2019-09-04 12:50
Issue still present on Instance level export

**Closed** 2019-09-04 14:48 UTC
Labels: bug
