### ISSUE TITLE
UI QIDO requests shall not contain proprietary Query Parameters with default values

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1962] opened 2019-04-30 07:52 UTC
UI QIDO requests shall **not** contain proprietary Query Parameters with default values:
- `returnempty=false`
- `compressionfailed=false`
- `storageVerificationFailed=false`

**Comment by vrindanayak** [comment] 2020-08-11 12:30
No longer reproducible. Seems to be fixed by some previous UI commit.

**Closed by vrindanayak** 2020-08-11 12:30 UTC
Labels: enhancement
