### ISSUE TITLE
Failed to respond to the client request

### ISSUE THREAD

**Issue by lixin1984** [dcm4che/dcm4chee-arc-light#2175] opened 2019-09-27 09:02 UTC
**Describe the question**
After deploying the system, importing the data through storescu,  found that the system process had opened many local connections. After some time, I found that the system would reject new client connection requests.  Please help me, thank you!

**Screenshots**
V5.14.1  wildfly-11.0.0.Final
![image](https://user-images.githubusercontent.com/55874294/65756057-ece67f80-e146-11e9-9a97-91cdeaa61ced.png)

V5.18.1：
keycloak-7.0.0
![image](https://user-images.githubusercontent.com/55874294/65756448-b3624400-e147-11e9-9ac3-b0c7901ecf8a.png)

wildfly-17.0.1.Final
![image](https://user-images.githubusercontent.com/55874294/65756518-d12fa900-e147-11e9-8671-14b98389a28c.png)

**Comment by lixin1984** [comment] 2019-09-30 00:16
The number of connections increases as the data is imported. When the import is stopped, the number of connections remains the same and does not decrease.

**Comment by lixin1984** [comment] 2019-09-30 01:50
After testing, it was found that after deploying the system, the system initialized to open a large number of local connections before importing the data.

**Comment by lixin1984** [comment] 2019-10-04 23:51
> After testing, it was found that after deploying the system, the system initialized to open a large number of local connections before importing the data.

When data is imported, the number of connections increases rapidly, but is not released.

**Comment by lixin1984** [comment] 2019-10-06 01:21
When the number of local connections increased to about 1.5K, the server failed to respond to the client request and reported an exception.
![image](https://user-images.githubusercontent.com/55874294/66262825-a8c83e80-e81a-11e9-857a-286c87c9e81f.png)

**Comment by gunterze** [comment] 2019-10-07 08:01
Cannot reproduce the issue:
Connections of archive docker container:
```
$ docker exec dcm4cheearc_arc_1 ss -ant
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port              
LISTEN     0      50           *:9990                     *:*                  
LISTEN     0      50           *:11112                    *:*                  
LISTEN     0      50     127.0.0.1:3528                     *:*                  
LISTEN     0      50           *:9993                     *:*                  
LISTEN     0      50           *:2575                     *:*                  
LISTEN     0      128          *:8080                     *:*                  
LISTEN     0      128    127.0.0.11:32784                    *:*                  
LISTEN     0      1            *:8787                     *:*                  
LISTEN     0      128          *:8443                     *:*                  
ESTAB      0      0      172.18.0.12:47254              172.18.0.7:5432               
ESTAB      0      0      172.18.0.12:42610              172.18.0.6:389                
CLOSE-WAIT 1      0      172.18.0.12:58414              192.168.2.145:8843               
ESTAB      0      0      172.18.0.12:36982              172.18.0.4:8514               
CLOSE-WAIT 1      0      172.18.0.12:58422              192.168.2.145:8843               
ESTAB      0      0      172.18.0.12:47286              172.18.0.7:5432 
```
```
$ docker exec dcm4cheearc_keycloak_1 ss -ant
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port              
LISTEN     0      50     172.18.0.8:8990                     *:*                  
LISTEN     0      50     172.18.0.8:8993                     *:*                  
LISTEN     0      128    127.0.0.11:44578                    *:*                  
LISTEN     0      128    172.18.0.8:8843                     *:*                  
LISTEN     0      128    172.18.0.8:8880                     *:*                  
ESTAB      0      0      172.18.0.8:57778              172.18.0.2:3306      
```
Which does not change after sending ~80000 objects in 100 associations.

We also have installations in productions running months without restart!

BTW, the association initiator is responsible for closing the TCP connection! You may configure an idle timeout of connctions of the archive, to force to abort idle associations opened by other DICOM Applications.

**Closed by gunterze** 2019-10-07 08:01 UTC

**Comment by lixin1984** [comment] 2019-10-08 04:31
@gunterze My deployment environment is a physical server. After starting the service, the service process opens many loopback links without any other clients.  At first I thought it was the VM link to ActiveMQ inside the system, but then I noticed that the keycloak process had also opened many loopback link.  And the number of loops opened per process is basically the same (keycloak : 272,  wildfly:  1050).
![image](https://user-images.githubusercontent.com/55874294/66367393-91c64f80-e9c6-11e9-97d2-be6aaa2daa57.png)
