### ISSUE TITLE
 Schedule Storage Commitment of matching Studies from external Storage Commitment SCP REST service : Misleading Log INFO message about `Suppress processing of already deleted Task` after task creation and before its subsequent processing

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4326] opened 2024-01-02 09:03 UTC
[Schedule Storage Commitment of matching Studies from external Storage Commitment SCP](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/STGCMT-RS/ScheduleStorageCommitmentOfMatchingStudiesExternal)

```
09:46:51,903 INFO  [org.dcm4chee.arc.stgcmt.rs.StgCmtSCUMatchingRS] (default task-7) Process POST /dcm4chee-arc/aets/DCM4CHEE/rs/studies/stgcmt/CENTRAL?ModalitiesInStudy=CR&PatientID=FUJI00007 from null@127.0.0.1
09:46:51,931 INFO  [org.dcm4chee.arc.qmgt.impl.TaskManagerEJB] (default task-7) Create Task{taskID=571, deviceName='dcm4chee-arc', queueName='StgCmtSCU', type=STGCMT_SCU, status=SCHEDULED, scheduledTime=Tue Jan 02 09:46:51 CET 2024, numberOfFailures=0, studyInstanceUID=1.2.392.200036.9125.0.199402091242.1, localAET=DCM4CHEE, remoteAET=CENTRAL}
09:46:51,939 INFO  [org.dcm4chee.arc.qmgt.impl.TaskManagerEJB] (EE-ManagedExecutorService-default-Thread-128) Suppress processing of already deleted Task[pk=571]
........
........
09:47:22,638 INFO  [org.dcm4chee.arc.qmgt.impl.TaskScheduler] (EE-ManagedScheduledExecutorService-default-Thread-14) start TaskScheduler.execute()
09:47:22,683 INFO  [org.dcm4chee.arc.qmgt.impl.TaskScheduler] (EE-ManagedScheduledExecutorService-default-Thread-14) finished TaskScheduler.execute()
09:47:22,704 INFO  [org.dcm4chee.arc.qmgt.impl.TaskScheduler] (EE-ManagedExecutorService-default-Thread-129) Start processing Task{taskID=571, deviceName='dcm4chee-arc', queueName='StgCmtSCU', type=STGCMT_SCU, status=IN PROCESS, scheduledTime=2024-01-02 09:46:51.91, numberOfFailures=0, studyInstanceUID=1.2.392.200036.9125.0.199402091242.1, localAET=DCM4CHEE, remoteAET=CENTRAL}
09:47:22,704 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-129) Initiate connection from /0.0.0.0:0 to demo2.j4care.com:11113
09:47:22,729 INFO  [org.dcm4che3.net.Connection] (EE-ManagedExecutorService-default-Thread-129) Established connection Socket[addr=demo2.j4care.com/116.202.148.152,port=11113,localport=60501]
09:47:22,729 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-129) DCM4CHEE->CENTRAL(10) << A-ASSOCIATE-RQ
09:47:22,752 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-130) DCM4CHEE->CENTRAL(10) >> A-ASSOCIATE-AC
09:47:22,759 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-129) DCM4CHEE->CENTRAL(10) << 1:N-ACTION-RQ[pcid=1, actionID=1
  cuid=1.2.840.10008.1.20.1 - Storage Commitment Push Model SOP Class
  iuid=1.2.840.10008.1.20.1.1 - Storage Commitment Push Model SOP Instance
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
09:47:22,800 INFO  [org.dcm4che3.net.Dimse] (EE-ManagedExecutorService-default-Thread-130) DCM4CHEE->CENTRAL(10) >> 1:N-ACTION-RSP[pcid=1, status=0H
  cuid=1.2.840.10008.1.20.1 - Storage Commitment Push Model SOP Class
  iuid=1.2.840.10008.1.20.1.1 - Storage Commitment Push Model SOP Instance
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
09:47:22,801 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-129) DCM4CHEE->CENTRAL(10) << A-RELEASE-RQ
09:47:22,806 INFO  [org.dcm4chee.arc.qmgt.impl.TaskManagerEJB] (EE-ManagedExecutorService-default-Thread-129) Finished processing of Task{taskID=571, deviceName='dcm4chee-arc', queueName='StgCmtSCU', type=STGCMT_SCU, status=COMPLETED, scheduledTime=2024-01-02 09:46:51.91, numberOfFailures=0, studyInstanceUID=1.2.392.200036.9125.0.199402091242.1, localAET=DCM4CHEE, remoteAET=CENTRAL}
09:47:22,825 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-130) DCM4CHEE->CENTRAL(10) >> A-RELEASE-RP
09:47:22,825 INFO  [org.dcm4che3.net.Association] (EE-ManagedExecutorService-default-Thread-130) DCM4CHEE->CENTRAL(10): close Socket[addr=demo2.j4care.com/116.202.148.152,port=11113,localport=60501]
```

**Comment by gunterze** [comment] 2024-01-02 09:55
Caused by  calling
```java
public class TaskManagerImpl implements TaskManager {
...
    public void scheduleTask(Task task) {
        ejb.scheduleTask(task);
        if (task.getScheduledTime().getTime() <= System.currentTimeMillis()) {
            processQueue(task.getQueueName());
        }
    }
```
in a existing Transaction propagated to `ejb.scheduleTask(task);` and also to `ejb.findTasksToProcess(queueName, fetchSize);` in
```java
public class TaskScheduler extends Scheduler {
...
    public void process(QueueDescriptor desc, int fetchSize) {
        String queueName = desc.getQueueName();
        if (desc.isInstalled() && !inProcess.contains(queueName)
                && ScheduleExpression.emptyOrAnyContainsNow(desc.getSchedules())) {
            if (rescheduleInProcess.add(queueName)) {
                ejb.rescheduleInProcess(queueName);
            }
            List<Long> pks = ejb.findTasksToProcess(queueName, fetchSize);
            if (!pks.isEmpty()) {
                device.execute(() -> process(desc, pks));
            }
        }
    }
```
but not to `process(desc, pks)` - because it's executed by a different thread - and therefore `em.find(Task.class, pk);` in
```java
public class TaskManagerEJB {
...
    public Task onProcessingStart(Long pk) {
        Task entity = em.find(Task.class, pk);
        if (entity == null) {
            LOG.info("Suppress processing of already deleted Task[pk={}]", pk);
        } else if (entity.getStatus() != Task.Status.SCHEDULED && entity.getStatus() != Task.Status.SCHEDULED_FOR_RETRY) {
            LOG.info("Suppress processing {}", entity);
        } else {
            entity.setProcessingStartTime(new Date());
            entity.setStatus(Task.Status.IN_PROCESS);
            return entity;
        }
        return null;
    }
```
does not find the inserted - but not yet committed - Task entity.

**Closed** 2024-01-02 10:04 UTC
Labels: bug
